# Generated by Django 5.0.9 on 2024-10-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secappweb',
        ),
    ]
