# Generated by Django 5.0.9 on 2024-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_secappweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('codusu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomusu', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255, unique=True)),
                ('tipcol', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=10, null=True)),
                ('numemp', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=255, null=True)),
                ('codfil', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('codloc', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=200, null=True)),
                ('numcad', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('numins', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'R999USU',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='R999Usu',
        ),
    ]
