# Generated by Django 5.0.9 on 2024-11-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplementoOp',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='OrdensProducao',
        ),
        migrations.DeleteModel(
            name='Origens',
        ),
        migrations.DeleteModel(
            name='RoteirosOP',
        ),
    ]
