# Generated by Django 5.0.9 on 2024-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('codemp', models.SmallIntegerField(db_column='usu_codemp')),
                ('numemb', models.BigIntegerField(db_column='usu_numemb')),
                ('veremb', models.SmallIntegerField(db_column='usu_veremb', primary_key=True, serialize=False)),
                ('coddep', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_coddep', max_length=10, null=True)),
                ('sitemb', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_sitemb', max_length=1, null=True)),
                ('embdis', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_embdis', max_length=1, null=True)),
                ('codpro', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codpro', max_length=14, null=True)),
                ('codlot', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codlot', max_length=50, null=True)),
                ('qtdemb', models.IntegerField(blank=True, db_column='usu_qtdemb', null=True)),
                ('etgatu', models.SmallIntegerField(blank=True, db_column='usu_etgatu', null=True)),
                ('hisatu', models.SmallIntegerField(blank=True, db_column='usu_hisatu', null=True)),
                ('qtdini', models.IntegerField(blank=True, db_column='usu_qtdini', null=True)),
                ('profim', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_profim', max_length=14, null=True)),
            ],
            options={
                'db_table': 'USU_TEmbalagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmbalagem',
            fields=[
                ('codemp', models.SmallIntegerField(db_column='usu_codemp')),
                ('numemb', models.BigIntegerField(db_column='usu_numemb')),
                ('veremb', models.SmallIntegerField(db_column='usu_veremb')),
                ('seqhis', models.SmallIntegerField(db_column='usu_seqhis', primary_key=True, serialize=False)),
                ('codori', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codori', max_length=3, null=True)),
                ('numorp', models.IntegerField(blank=True, db_column='usu_numorp', null=True)),
                ('codetg', models.SmallIntegerField(blank=True, db_column='usu_codetg', null=True)),
                ('seqrot', models.SmallIntegerField(blank=True, db_column='usu_seqrot', null=True)),
                ('codopr', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codopr', max_length=6, null=True)),
                ('seqeoq', models.IntegerField(blank=True, db_column='usu_seqeoq', null=True)),
                ('seqrfg', models.IntegerField(blank=True, db_column='usu_seqrfg', null=True)),
                ('codpro', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codpro', max_length=14, null=True)),
                ('codcre', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codcre', max_length=8, null=True)),
                ('codmol', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codmol', max_length=50, null=True)),
                ('codlot', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_codlot', max_length=50, null=True)),
                ('qtdhis', models.IntegerField(blank=True, db_column='usu_qtdhis', null=True)),
                ('qtdrfg', models.IntegerField(blank=True, db_column='usu_qtdrfg', null=True)),
                ('tiphis', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_tiphis', max_length=1, null=True)),
                ('numcad', models.IntegerField(blank=True, db_column='usu_numcad', null=True)),
                ('depini', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_depini', max_length=10, null=True)),
                ('datger', models.DateField(blank=True, db_column='usu_datger', null=True)),
                ('horger', models.IntegerField(blank=True, db_column='usu_horger', null=True)),
                ('usuger', models.BigIntegerField(blank=True, db_column='usu_usuger', null=True)),
                ('deprec', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='usu_deprec', max_length=10, null=True)),
                ('datrec', models.DateField(blank=True, db_column='usu_datrec', null=True)),
                ('horrec', models.IntegerField(blank=True, db_column='usu_horrec', null=True)),
                ('usurec', models.BigIntegerField(blank=True, db_column='usu_usurec', null=True)),
            ],
            options={
                'db_table': 'USU_THistEmb',
                'managed': False,
            },
        ),
    ]
